config/routes.rb
Rails.application.routes.draw do
  resources :surveys do
    collection do
      get 'list'
    end
  end
  resources :questions do
    resources :answers
  end

  get 'home/index'
  devise_for :users
  root to: 'surveys#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  validates_presence_of :text
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  has_many :answers
  accepts_nested_attributes_for :answers, allow_destroy: true
  validates_presence_of :text
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :questions
  accepts_nested_attributes_for :questions, allow_destroy: true
  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:survey_taker, :survey_admin]
  after_initialize :set_default_role, :if => :new_record?
  has_many :answers

  # Sets the default role
  def set_default_role
    self.role ||= :survey_taker
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(answer_parameters)
    @answer.user = current_user
    @answer.save

    redirect_to @question
  end

  private

  def answer_parameters
    params.require(:answer).permit(:text, :user_id, :question_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_before_action :authenticate_user, only: [:create, :destroy], raise: false

  def index
    @question = Question.all

    render json: @question
  end

  def show
    @question = Question.find(params[:id])
  end

  def create
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions.build(question_parameters)
    if @question.save
      render json: @survey, status: :created
    else
      render json: @survey.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    head :no_content
  end

  private

  def question_parameters
    params.require(:question).permit(:text)
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  skip_before_action :authenticate_user, only: [:list], raise: false
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  def index
    @surveys = Survey.all
  end

  def list
    @surveys = Survey.all
    render json: {status: 'SUCCESS', message: ' List of All Surveys', data: @surveys}, status: :ok
  end

  def show
  end

  def new
    @survey = Survey.new
  end

  def edit
  end

  def create
    @survey = Survey.new(survey_parameters)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey created!!' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @survey.update(survey_parameters)
        format.html { redirect_to @survey, notice: 'Survey updated!!' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey destroyed!!' }
      format.json { head :no_content }
    end
  end

  private

  def set_survey
    @survey = Survey.find(params[:id])
  end

  def survey_parameters
    params.require(:survey).permit(:name, :questions_attributes =>  [:id, :text, :_destroy])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark bg-dark navbar-fixed-top navbar-expand-lg">
  <a class="navbar-brand" href="/">Survey Application</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "My Account", edit_user_registration_path(current_user.id), class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Create Survey", new_survey_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', destroy_user_session_path, :method=>'delete', class: "nav-link" %>
          </li>
      <% else %>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class: "nav-link" %>
          </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SurveyApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <div class="container">
      <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/show.html.erb
<h1><%= @question.content %></h1>
<h6>List of Answers</h6>
<ol class="answers">
<% @question.answers.each do |answer| %>
    <li>
      <%= answer.text %> <br>
      <%= answer.user.email%>
    </li>
<% end %>
<h3> New Answer</h3>
<div class="form-actions">
  <%= form_for [@question, @question.answers.build] do |f| %>
      <%= f.text_area :text, :size => '40*10' %>
      <br>
      <%= f.submit "Submit Answer", :class => 'btn btn-large btn-primary' %>
  <% end %>
</div>
</ol>
<%= link_to 'Back to Surveys', surveys_path, class: "btn btn-secondary" %>

app/views/surveys/_form.html.erb
<%= form_with(model: survey, local: true) do |f| %>
  <% if survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
        <% survey.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, id: :survey_name %>
  </div>
  <%= f.fields_for :question do |builder| %>
    <%= render 'questions', f: builder %>
  <% end %>
  <br>
  <hr>
  <div class="actions">
    <%= f.submit class: 'btn btn-success'%>
    <% if !@survey.new_record?%>
    <%= link_to 'Show', @survey, class: "btn btn-info"%>
    <%= link_to 'Back', surveys_path, class: "btn btn-secondary" %>
    <% end %>
  </div>
<% end %>

app/views/surveys/_questions.html.erb
<fieldset>
  <%= f.label :text, "Question" %><br />
  <%= f.text_area :text, :size => '30*30'%><br />
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove Question" %>
</fieldset>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form', survey: @survey %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of Surveys</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @surveys.each do |survey| %>
      <tr>
        <td><%= link_to survey.name, survey %></td>
        <td><%= pluralize(survey.questions.size, "Question") %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey), class: "btn btn-primary" %></td>
        <td><%= link_to 'Delete', survey, :method => :delete, :confirm => "Are you sure?", class: "btn btn-danger"%></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<h1><%= @survey.name %></h1>

<ol class="questions">
  <% @survey.questions.each do |question| %>
      <li>
        <%= question.text %> <%= link_to "View Details", question %>
      </li>
  <% end %>
</ol>
<% if current_user.role == "survey_admin"%>
    <%= link_to 'Edit', edit_survey_path(@survey), class: "btn btn-primary"%>
    <%= link_to 'Back to Surveys', surveys_path, class: "btn btn-secondary" %>
<% end %>